jdbc:
  driver: com.mysql.jdbc.Driver
  username: root
  password: root
  url: jdbc:mysql://127.0.0.1:3306/tyut?useUnicode=true&characterEncoding=utf-8&useSSL=false

tyut:
  config:
    server:
      name: tyut-config-server
      port: 9000
  registry-conter:
    server1:
      host: localhost
      port: 8001
    server2:
      host: localhost
      port: 8002
    server3:
      host: localhost
      port: 8003
  services:
    grade:
      port: 10001
      name: tyut-grade-service
    notice:
      port: 10002
      name: tyut-notice-service
    onekey:
      port: 10003
      name: tyut-onekey-service
    user:
      port: 10004
      name: tyut-user-service