spring:
  profiles:
    active: native
  application:
    name: tyut-config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:config/
server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8001/eureka
  instance:
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1

